# This is a config for E2B sandbox template.
# You can use template ID (83ageoygk5i57r6127mb) or template name (vybe-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vybe-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vybe-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vybe-nextjs-test-2')

team_id = "6fcf5fbd-562d-4141-90e4-c4851cd2697a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vybe-nextjs-test-2"
template_id = "83ageoygk5i57r6127mb"
